# Generated by Django 4.1.1 on 2022-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
